// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Chat(arg1:main.ChatRequest):Promise<main.ChatResponse>;

export function GetTools():Promise<Array<main.ToolMetadata>>;

export function Greet(arg1:string):Promise<string>;

export function Models(arg1:main.ModelsRequest):Promise<main.ModelsResponse>;

export function SetToolEnabled(arg1:main.SetToolEnabledRequest):Promise<Array<main.ToolMetadata>>;
