// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {llm} from '../models';
import {tools} from '../models';
import {context} from '../models';

export function CancelChat(arg1:string):Promise<boolean>;

export function Chat(arg1:llm.ChatRequest):Promise<llm.ChatResponse>;

export function GetTools():Promise<Array<tools.ToolMetadata>>;

export function Greet(arg1:string):Promise<string>;

export function Models(arg1:llm.ModelsRequest):Promise<llm.ModelsResponse>;

export function RequestContinuation(arg1:context.Context,arg2:string,arg3:llm.ContinuationRequest):Promise<llm.ContinuationDecision>;

export function ResolveContinuation(arg1:llm.ContinuationDecisionRequest):Promise<boolean>;

export function RunShellCommand(arg1:string,arg2:Array<string>,arg3:boolean):Promise<string>;

export function SetToolEnabled(arg1:tools.SetToolEnabledRequest):Promise<Array<tools.ToolMetadata>>;
