// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Chat(arg1) {
  return window['go']['main']['App']['Chat'](arg1);
}

export function GetTools() {
  return window['go']['main']['App']['GetTools']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Models(arg1) {
  return window['go']['main']['App']['Models'](arg1);
}

export function SetToolEnabled(arg1) {
  return window['go']['main']['App']['SetToolEnabled'](arg1);
}
